#!python
# coding=utf8

import config

adminmenus = {
    "name":"admin", 
    "display":"管理员", 
    "href":"/admin",
    "menus":[{"name":"admin", "display":"管理", "href":"/admin",
        'submenus':[
            {"name":"service", "display":"服务", "href":"#admin-service"},
            {"name":"host", "display":"机器", "href":"#admin-host"},
            {"name":"task", "display":"任务", "href":"#admin-task"},
            {"name":"setting", "display":"设置", "href":"#admin-setting"},
            {"name":"template", "display":"模板", "href":"#admin-template"}
        ]
    }]
}

adminmenus['is_manager'] = config.install_manager
adminmenus['is_monitor'] = config.install_monitor

if config.install_monitor:
    adminmenus['menus'].append({"name":"monitor", "display":"监控", "href":"#/monitor",
        'submenus':[
            {"name":"mOverview", "display":'概览', "href":"#/monitor/overview",
                "tabs": [
                    {"name":"mtCurent", "display":"当前状态", "href":"/statics/partials/monitor/overview.html"},
                    {"name":"mtHistory", "display":"历史状态", "href":"/statics/partials/monitor/overview_history.html"},
                    {"name":"mtAlarmList", "display":"告警列表", "href":"/statics/partials/monitor/overview_alarms.html"}
                ]
            },
            {"name":"mHost", "display":"机器", "href":"#/monitor/host",
                "tabs": [
                    {"name":"mtHostsOverview", "display":"概览", "href":"/statics/partials/monitor/host_overview.html"},
                    {"name":"mtHostsMetric", "display":"监控指标", "href":"/statics/partials/monitor/host.html"},
                    {"name":"mtHostMetrics", "display":"监控机器", "href":"/statics/partials/monitor/host_host.html"}
                ]
            },
            {"name":"mService", "display":"服务", "href":"#/monitor/service",
                "tabs": [
                    {"name":"mtServiceOverview",    "display":"服务概览", "href":"/statics/partials/monitor/service_overview.html"},
                    {"name":"mtServiceHostsMetric", "display":"服务指标", "href":"/statics/partials/monitor/host.html"},
                    {"name":"mtServiceHostMetrics", "display":"服务实体", "href":"/statics/partials/monitor/host_host.html"}
                ]
            },
            {"name":"mJob", "display":"作业", "href":"#/monitor/job",
                "tabs": [
                    {"name":"mtJobRun", "display":"当前作业", "href":"/statics/partials/monitor/job.html"},
                    {"name":"mtJobRm", "display":"RM指标", "href":"/statics/partials/monitor/rm.html"},
                    {"name":"mtJobNm", "display":"NM指标", "href":"/statics/partials/monitor/nm.html"},
                    {"name":"mtJobApp", "display":"应用查询", "href":"/statics/partials/monitor/app.html"}
                ]
            },
            {"name":"mConf", "display":"配置", "href":"#/monitor/conf",
                "tabs": [
                    {"name":"mtMetric",         "display":"监控项",       "href":"/statics/partials/monitor/conf.html", "func":"query_monitor_metric()"},
                    {"name":"mtMetricGroup",    "display":"监控组",       "href":"/statics/partials/monitor/conf.html", "func":"query_monitor_group()"},
                    {"name":"mtMetricHost",     "display":"监控部署",     "href":"/statics/partials/monitor/conf.html", "func":"query_monitor_host()"},
                    {"name":"mtMetricPubVar",   "display":"监控公共变量", "href":"/statics/partials/monitor/conf.html", "func":"query_global_variate()"},
                    {"name":"mtAlarm",          "display":"告警配置",     "href":"/statics/partials/monitor/conf.html", "func":"query_alarm()"},
                    {"name":"mtAlarmAssist",    "display":"告警公共变量", "href":"/statics/partials/monitor/conf.html", "func":"query_alarm_assist()"}
                ]
            }
        ]
    })



usermenus = {"name":"user", "display":"用户", "href":"/user",
        "submenus":[
            #{"name":"info", "display":"概况", "href":"#user-info"},
            {"name":"hdfs", "display":"存储", "href":"#user-hdfs"},
            {"name":"yarn", "display":"作业", "href":"#user-yarn"}
            ]    
         }


#由于基本不修改，所以不存放在数据库
#保存了所有的素服和角色
services = [
    {"name":"ganglia", 
     "role": ["gmond","gmetad"],
     "actions":[{"name":"start","display":"启动","tooptip":"启动集群"},
                {"name":"stop","display":"停止","tooptip":"关闭集群"},
                {"name":"restart","display":"重启","tooptip":"重启集群"}], 
     "instanceActions":[{"name":"start","display":"启动","tooptip":""},
                        {"name":"stop","display":"停止","tooptip":""},
                        {"name":"restart","display":"重启","tooptip":""}],
     "dependence" : []
     },
    {"name":"zookeeper", 
     "role": ["zookeeper"],
     "actions":[{"name":"init","display":"初始化","tooptip":"创建目录，初始化myid"},
                {"name":"start","display":"启动","tooptip":"启动集群"},
                {"name":"stop","display":"停止","tooptip":"关闭集群"},
                {"name":"restart","display":"重启","tooptip":"重启集群"}], 
     "instanceActions":[{"name":"init","display":"初始化","tooptip":"创建目录，初始化myid"},
                        {"name":"start","display":"启动","tooptip":""},
                        {"name":"stop","display":"停止","tooptip":""},
                        {"name":"restart","display":"重启","tooptip":""}],
     "dependence" : []
     },
    {"name":"hdfs", 
     "role": ["qjm","namenode","datanode"],
     "actions":[{"name":"format","display":"格式化","tooptip":"格式化所有组件。谨慎执行！"},
                {"name":"init","display":"初始化","tooptip":"创建角色需要的目录"},
                {"name":"start","display":"启动","tooptip":""},
                {"name":"stop","display":"停止","tooptip":""},
                {"name":"restart","display":"重启","tooptip":""},
                {"name":"rollrestart","display":"滚动重启","tooptip":"滚动重启所有的datanode."},
                {"name":"initha","display":"重置HA","tooptip":"分发hdfs的SSH，重置在ZK的HA状态。"},
                {"name":"check","display":"检查","tooptip":"执行读写操作，检查是否可用。"}], 
     "instanceActions":[{"name":"init","display":"初始化","tooptip":""},
                        {"name":"start","display":"启动","tooptip":""},
                        {"name":"stop","display":"停止","tooptip":""},
                        {"name":"restart","display":"重启","tooptip":""}],
     "dependence" : ["zookeeper"],
     "web" : [{"role":"namenode","port":"dfs_namenode_http_address_port"}]
     },
    {"name":"yarn", 
     "role": ["resourcemanager","nodemanager","historyserver"],
     "actions":[{"name":"init","display":"初始化","tooptip":"创建必要的hdfs目录和NM的本地目录"},
                {"name":"start","display":"启动","tooptip":""},
                {"name":"stop","display":"停止","tooptip":""},
                {"name":"restart","display":"重启","tooptip":""},
                {"name":"rollrestart","display":"滚动重启","tooptip":"滚动重启所有的nodemanager。"},
                {"name":"check","display":"检查","tooptip":"提交一个YARN作业并运行。"},
                {"name":"scheduler","display":"刷新调度器","tooptip":"刷新调度器配置"}],
     "instanceActions":[{"name":"init","display":"初始化","tooptip":""},
                        {"name":"start","display":"启动","tooptip":""},
                        {"name":"stop","display":"停止","tooptip":""},
                        {"name":"restart","display":"重启","tooptip":""}],
     "dependence" : ["zookeeper","hdfs"],
     "web" : [{"role":"resourcemanager","port":"yarn_rm_webapp_port"},
              {"role":"historyserver","port":"mapreduce_jobhistory_webapp_port"}]
     },
    {"name":"hbase",
     "role":["hbasemaster","regionserver"],
     "actions":[{"name":"init","display":"初始化","tooptip":"创建hbase所需要的hdfs目录。"},
                {"name":"start","display":"启动","tooptip":""},
                {"name":"stop","display":"停止","tooptip":""},
                {"name":"restart","display":"重启","tooptip":""},
                {"name":"check","display":"检查","tooptip":"执行hbase的基本操作，检查hbase是否可用。"}], 
     "instanceActions":[{"name":"start","display":"启动","tooptip":""},
                        {"name":"stop","display":"停止","tooptip":""},
                        {"name":"restart","display":"重启","tooptip":""}],
     "dependence" : ["zookeeper","hdfs"],
     "web" : [{"role":"hbasemaster","port":"hbase_master_info_port"},
              {"role":"regionserver","port":"hbase_resigionserver_info_port"}]
     },
    {"name":"hive",
     "role":["hiveserver","hiveserver2","hivemetastore"],
     "actions":[{"name":"initmysql","display":"格式化数据库","tooptip":"初始化hive的元数据库。"},
                {"name":"init","display":"初始化","tooptip":"创建HDFS目录。"},
                {"name":"start","display":"启动","tooptip":""},
                {"name":"stop","display":"停止","tooptip":""},
                {"name":"restart","display":"重启","tooptip":""},
                {"name":"check","display":"检查","tooptip":"执行hive的sql语句，检查hive是否可用。"}], 
     "instanceActions":[{"name":"start","display":"启动","tooptip":""},
                        {"name":"stop","display":"停止","tooptip":""},
                        {"name":"restart","display":"重启","tooptip":""}],
     "dependence" : ["hdfs","yarn"]
     },   
     {"name":"impala",
     "role":["impalastatestore","impalaserver"],
     "actions":[{"name":"init","display":"初始化","tooptip":""},
                {"name":"start","display":"启动","tooptip":""},
                {"name":"stop","display":"停止","tooptip":""},
                {"name":"restart","display":"重启","tooptip":""},
                {"name":"check","display":"检查","tooptip":"执行简单查询,检查impala是否可用。"}
                ], 
     "instanceActions":[{"name":"init","display":"初始化","tooptip":""},
                        {"name":"start","display":"启动","tooptip":""},
                        {"name":"stop","display":"停止","tooptip":""},
                        {"name":"restart","display":"重启","tooptip":""}],
     "dependence" : ["hdfs","hive"],
     "web" : [{"role":"impalastatestore","port":"impala_state_store_web_port"}]
     },     
     {"name":"client",
     "role":["zookeeper-client","hadoop-client","hbase-client","hive-client","impala-client"],
     "actions":[], 
     "instanceActions":[{"name":"config","display":"分发配置","tooptip":"分发配置文件"}],
     "dependence" : []
     },       
    ]   

role_check_map = { 
    "zookeeper" : { "min" : 1 },
    "qjm" : { "min" : 1 },
    "namenode" : { "equal" : 2 },
    "datanode" : { "min" : 1 },
    "resourcemanager" : { "equal" : 1 }, 
    "nodemanager" : { "min" : 1 }, 
    "historyserver" : { "equal" : 1 }, 
    }

def get_service_from_role(role):
    for service in services:
        if role in service['role']:
            return service['name']

def get_role_from_service(now):
    for service in services:
        if service['name'] == now:
            return service['role']

# 监控的配置项母本

monitor_show_info={
    'metrics':{
        'default':[
            {'name':'load_one','display':'一分钟负载'},
            {'name':'load_five','display':'五分钟负载'},
            {'name':'load_fifteen','display':'十五分钟负载'},
            {'name':'mem_total', 'display':'物理内存总量（KBs显示）'},
            {'name':'mem_cached', 'display':'缓存内存大小'},
            {'name':'mem_free', 'display':'空闲内存大小'},
            {'name':'mem_buffers', 'display':'内核缓存的内存总量'},
            {'name':'mem_shared', 'display':'共享内存大小'},
            {'name':'swap_total', 'display':'交换分区总量（KBs显示）'},
            {'name':'swap_free', 'display':'空闲交换分区大小'},
            {'name':'proc_run', 'display':'运行的进程总数'},
            {'name':'proc_total', 'display':'进程总数'},
            {'name':'cpu_idle', 'display':'空闲CPU百分比'},
            {'name':'cpu_aidle', 'display':'启动的空闲CPU百分比'},
            {'name':'cpu_user', 'display':'用户空间占用CPU百分比'},
            {'name':'cpu_nice', 'display':'用户进程空间内改变过优先级的进程占用CPU百分比'},
            {'name':'cpu_system', 'display':'内核空间占用CPU百分比'},
            {'name':'cpu_num', 'display':'CPU线程总数'},
            {'name':'cpu_speed', 'display':'CPU速度（MHz）'},
            {'name':'cpu_wio', 'display':'Cpu空闲时的最大I/O请求'},
            {'name':'part_max_used', 'display':'Maximumpercentusedforallpartitions'},
            {'name':'disk_total', 'display':'磁盘总大小'},
            {'name':'disk_free', 'display':'剩余磁盘空间'},
            {'name':'boottime', 'display':'系统启动时间'},
            {'name':'pkts_in', 'display':'每秒进来的包'},
            {'name':'pkts_out', 'display':'每秒出去的包'},
            {'name':'bytes_in', 'display':'每秒进来字节数'},
            {'name':'bytes_out', 'display':'每秒出去字节数'},
            {'name':'machine_type', 'display':'系统版本（X86或64）'},
            {'name':'os_name', 'display':'系统名字'},
            {'name':'os_release', 'display':'系统版本'},
            {'name':'gexec', 'display':'gexecavailable'},
            {'name':'disk_free_rootfs', 'display':'Diskspaceavailableon'}
        ],
    
        'default-ext':[
            {'name':'dev-sda1-disk_total', 'display':'各个分区的容量'},
            {'name':'dev-sda1-disk_used', 'display':'各个分区的使用量'},
            {'name':'tcp_established', 'display':'established状态的TCP连接的数量'},
            {'name':'tcp_listen', 'display':'listen状态的TCP连接的数量'},
            {'name':'tcp_timewait', 'display':'timewait状态的TCP连接的数量'},
            {'name':'tcp_closewait', 'display':'closewait状态的TCP连接的数量'},
            {'name':'tcp_synsent', 'display':'synsent状态的TCP连接的数量'},
            {'name':'tcp_synrecv', 'display':'synrecv状态的TCP连接的数量'},
            {'name':'tcp_synwait', 'display':'synwait状态的TCP连接的数量'},
            {'name':'tcp_finwait1', 'display':'finwait1状态的TCP连接的数量'},
            {'name':'tcp_finwait2', 'display':'finwait2状态的TCP连接的数量'},
            {'name':'tcp_closed', 'display':'closed状态的TCP连接的数量'},
            {'name':'tcp_lastack', 'display':'lastack状态的TCP连接的数量'},
            {'name':'tcp_closing', 'display':'closing状态的TCP连接的数量'},
            {'name':'tcp_unknown', 'display':'unknown状态的TCP连接的数量'},
        ],
    
        'hadoop-dfs-namenode':[
            {'name':'dfs.namenode.BlockReportAvgTime', 'display':'块汇报的平均时间'},
            {'name':'dfs.namenode.BlockReportNumOps', 'display':'块汇报的操作次数'},
            {'name':'dfs.namenode.fsImageLoadTime', 'display':'启动时候的image加载时间'},
            {'name':'dfs.namenode.safeModeTime', 'display':'启动时候的safemode的时长'}, 
            {'name':'dfs.namenode.SyncsAvgTime', 'display':'Syncs操作平均时间'},
            {'name':'dfs.namenode.SyncsNumOps', 'display':'Syncs操作次数'},
            {'name':'dfs.namenode.TransactionsAvgTime', 'display':'事务平均时间'},
            {'name':'dfs.namenode.TransactionsNumOps', 'display':'事务操作次数'},
            {'name':'dfs.NameNode.CurrentLagTxns', 'display':'当前最大事务编号'},
            {'name':'dfs.NameNode.LagTimeMillis', 'display':'dfs.NameNode.LagTimeMillis'},
            {'name':'dfs.NameNode.QueuedEditsSize', 'display':'dfs.NameNode.QueuedEditsSize'}, 
            {'name':'dfs.namenode.createFileOps', 'display':'创建文件的操作'},
            {'name':'dfs.namenode.filesAppended', 'display':'文件追加的次数'}, 
            {'name':'dfs.namenode.getBlockLocations', 'display':'获取block位置'}, 
            {'name':'dfs.namenode.filesRenamed', 'display':'文件重命名次数'},
            {'name':'dfs.namenode.getListingOps', 'display':'获取目录列表次数'},
            {'name':'dfs.namenode.filesInGetListingOps', 'display':'获取目录列表长度总和'},
            {'name':'dfs.namenode.deleteFileOps', 'display':'删除文件操作次数'},
            {'name':'dfs.namenode.filesDeleted', 'display':'文件或者目录被删除或者重命名的次数'},
            {'name':'dfs.namenode.fileInfoOps', 'display':'获取文件信息的操作次数'},
            {'name':'dfs.namenode.addBlockOps', 'display':'添加一个块的操作次数'},
            {'name':'dfs.namenode.getAdditionalDatanodeOps', 'display':'获取当前datanode的状况'},
            {'name':'dfs.namenode.createSymlinkOps', 'display':'创建文件软连接的次数'},
            {'name':'dfs.namenode.getLinkTargetOps', 'display':'获取文件的软连接的次数'},
            {'name':'dfs.namenode.transactions', 'display':'NM进行事务的速率'},
            {'name':'dfs.namenode.syncs', 'display':'NM进行sync的速率'},
            {'name':'dfs.namenode.syncsQuantiles', 'display':'NM进行sync的时间分布'},
            {'name':'dfs.namenode.transactionsBatchedInSync', 'display':'同步的事务数量'},
            {'name':'dfs.namenode.blockReport', 'display':'进行块报告的速率'},
            {'name':'dfs.namenode.blockReportQuantiles', 'display':'块报告的进行的数据分布'},
        ],
    
        'hadoop-dfs-FSNamesystem': [
            {'name':'dfs.FSNamesystem.BlockCapacity', 'display':'通过计算得到block'},
            {'name':'dfs.FSNamesystem.BlocksTotal', 'display':'总的块数量'},
            {'name':'dfs.FSNamesystem.CapacityRemainingGB', 'display':'可用空间GB'},
            {'name':'dfs.FSNamesystem.CapacityTotalGB', 'display':'总存储量GB'},
            {'name':'dfs.FSNamesystem.CapacityUsedGB', 'display':'总使用量GB'},
            {'name':'dfs.FSNamesystem.CorruptBlocks', 'display':'损坏的块数'},
            {'name':'dfs.FSNamesystem.ExcessBlocks', 'display':'过量的块的数量'},
            {'name':'dfs.FSNamesystem.ExpiredHeartbeats', 'display':'超时心跳的数量'},
            {'name':'dfs.FSNamesystem.FilesTotal', 'display':'总的inode数量'},
            {'name':'dfs.FSNamesystem.LastCheckpointTime', 'display':'上次checkpoint至今的时间'},
            {'name':'dfs.FSNamesystem.LastWrittenTransactionId', 'display':'上次editlog写入的事务id'},
            {'name':'dfs.FSNamesystem.MillisSinceLastLoadedEdits', 'display':'距离上次同步editlog的毫秒数'},
            {'name':'dfs.FSNamesystem.MissingBlocks', 'display':'丢失块的数量'},
            {'name':'dfs.FSNamesystem.PendingDataNodeMessageCount', 'display':'待发送给datanode的命令的数量。'},
            {'name':'dfs.FSNamesystem.PendingDeletionBlocks', 'display':'待删除的块的数量'},
            {'name':'dfs.FSNamesystem.PendingReplicationBlocks', 'display':'待复制的块数量'},
            {'name':'dfs.FSNamesystem.PostponedMisreplicatedBlocks', 'display':'缺块或者多块的block的数量'},
            {'name':'dfs.FSNamesystem.ScheduledReplicationBlocks', 'display':'正在复制的块的数量'},
            {'name':'dfs.FSNamesystem.TotalFiles', 'display':'获取总的文件数量'},
            {'name':'dfs.FSNamesystem.TotalLoad', 'display':'获取所有的datanode的Xceiver的总数量'},
            {'name':'dfs.FSNamesystem.TransactionsSinceLastCheckpoint', 'display':'上次checkpoint后的事务数量'},
            {'name':'dfs.FSNamesystem.TransactionsSinceLastLogRoll', 'display':'上次editlog滚动后的事务数量'},
            {'name':'dfs.FSNamesystem.UnderReplicatedBlocks', 'display':'小于副本数的块数量'},
            {'name':'dfs.FSNamesystem.MissingBlocksCount', 'display':'丢失块的数量'},
            {'name':'dfs.FSNamesystem.CorruptReplicaBlocks', 'display':'丢失的块的数量'},
            {'name':'dfs.FSNamesystem.HAState', 'display':'HA的状态'},
        ],
    
        'hadoop-dfs-datanode':[
            {'name':'dfs.datanode.BlockReportsAvgTime', 'display':'块报告平均时间'},
            {'name':'dfs.datanode.BlockReportsNumOps', 'display':'块报告次数'},
            {'name':'dfs.datanode.HeartbeatsAvgTime', 'display':'向namenode汇报平均时间'},
            {'name':'dfs.datanode.HeartbeatsNumOps', 'display':'向namenode汇报总次数'},
            {'name':'dfs.datanode.blockChecksumOp_avg_time', 'display':'块校验平均时间'},
            {'name':'dfs.datanode.blockChecksumOp_num_ops', 'display':'块检验次数'},
            {'name':'dfs.datanode.blockReports_avg_time', 'display':'块报告平均时间'},
            {'name':'dfs.datanode.blockReports_num_ops', 'display':'块报告次数'},
            {'name':'dfs.datanode.block_verification_failures', 'display':'块验证失败次数'},
            {'name':'dfs.datanode.blocks_read', 'display':'从硬盘读块总次数'},
            {'name':'dfs.datanode.blocks_removed', 'display':'删除块数目'},
            {'name':'dfs.datanode.blocks_replicated', 'display':'块复制总次数'},
            {'name':'dfs.datanode.blocks_verified', 'display':'块验证总次数'},
            {'name':'dfs.datanode.blocks_written', 'display':'向硬盘写块总次数'},
            {'name':'dfs.datanode.bytes_read', 'display':'读出总字节'},
            {'name':'dfs.datanode.bytes_written', 'display':'写入总字节数'},
            {'name':'dfs.datanode.copyBlockOp_avg_time', 'display':'复制块平均时间'},
            {'name':'dfs.datanode.copyBlockOp_num_ops', 'display':'复制块次数'},
            {'name':'dfs.datanode.heartBeats_avg_time', 'display':'向namenode汇报平均时间'},
            {'name':'dfs.datanode.heartBeats_num_ops', 'display':'向namenode汇报总次数'},
            {'name':'dfs.datanode.readBlockOp_avg_time', 'display':'读块平均时间（单位ms）'},
            {'name':'dfs.datanode.readBlockOp_num_ops', 'display':'读块总次数'},
            {'name':'dfs.datanode.reads_from_local_client', 'display':'从本地读入块次数'},
            {'name':'dfs.datanode.reads_from_remote_client', 'display':'从远程读入块次数'},
            {'name':'dfs.datanode.replaceBlockOp_avg_time', 'display':'替换块平均时间（负载均衡策略）'},
            {'name':'dfs.datanode.replaceBlockOp_num_ops', 'display':'替换块次数（负载均衡策略）'},
            {'name':'dfs.datanode.volumeFailures', 'display':'失败的卷数'},
            {'name':'dfs.datanode.writeBlockOp_avg_time', 'display':'写块平均时间'},
            {'name':'dfs.datanode.writeBlockOp_num_ops', 'display':'写块总次数'},
            {'name':'dfs.datanode.writes_from_local_client', 'display':'写本地次数'},
            {'name':'dfs.datanode.writes_from_remote_client', 'display':'写远程次数'},
        ],
    
        'jvm-ProcessName':[
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.GcCountConcurrentMarkSweep', 'display':'DataNode ConcurrentMarkSweep GC数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.GcCountCopy', 'display':'DataNode GC拷贝数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.GcCount', 'display':'DataNode GC数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.GcTimeMillisConcurrentMarkSweep', 'display':'DataNode ConcurrentMarkSweep GC用时'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.GcTimeMillisCopy', 'display':'DataNode GC拷贝用时'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.GcTimeMillis', 'display':'DataNode GC用时'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.LogError', 'display':'DataNode 出现Error记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.LogFatal', 'display':'DataNode 出现Fatal记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.LogInfo', 'display':'DataNode 出现Info记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.LogWarn', 'display':'DataNode 出现Warn记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.MemHeapCommittedM', 'display':'DataNode jvm提交堆内存大小'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.MemHeapUsedM', 'display':'DataNode jvm使用堆内存大小'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.MemNonHeapCommittedM', 'display':'DataNode jvm非堆内存已提交大小'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.MemNonHeapUsedM', 'display':'DataNode jvm非堆内存已使用大小'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.ThreadsBlocked', 'display':'DataNode 阻塞等待监视器锁的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.ThreadsNew', 'display':'DataNode 尚未启动的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.ThreadsRunnable', 'display':'DataNode 正在执行状态的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.ThreadsTerminated', 'display':'DataNode 已退出线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.ThreadsTimedWaiting', 'display':'DataNode 等待并指定了等待时间的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=DataNode.ThreadsWaiting', 'display':'DataNode 无限期地等待特定操作的线程数目'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.GcCountConcurrentMarkSweep', 'display':'NameNode ConcurrentMarkSweep GC数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.GcCountCopy', 'display':'NameNode GC拷贝数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.GcCount', 'display':'NameNode GC数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.GcTimeMillisConcurrentMarkSweep', 'display':'NameNode ConcurrentMarkSweep GC用时'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.GcTimeMillisCopy', 'display':'NameNode GC拷贝用时'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.GcTimeMillis', 'display':'NameNode GC用时'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.LogError', 'display':'NameNode 出现Error记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.LogFatal', 'display':'NameNode 出现Fatal记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.LogInfo', 'display':'NameNode 出现Info记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.LogWarn', 'display':'NameNode 出现Warn记录数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.MemHeapCommittedM', 'display':'NameNode jvm提交堆内存大小'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.MemHeapUsedM', 'display':'NameNode jvm使用堆内存大小'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.MemNonHeapCommittedM', 'display':'NameNode jvm非堆内存已提交大小'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.MemNonHeapUsedM', 'display':'NameNode jvm非堆内存已使用大小'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.ThreadsBlocked', 'display':'NameNode 阻塞等待监视器锁的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.ThreadsNew', 'display':'NameNode 尚未启动的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.ThreadsRunnable', 'display':'NameNode 正在执行状态的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.ThreadsTerminated', 'display':'NameNode 已退出线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.ThreadsTimedWaiting', 'display':'NameNode 等待并指定了等待时间的线程数'},
            {'name':'jvm.JvmMetrics.ProcessName=NameNode.ThreadsWaiting', 'display':'NameNode 无限期地等待特定操作的线程数目'},
            {'name':'jvm.metrics.gcCount', 'display':'gc总次数'},
            {'name':'jvm.metrics.gcTimeMillis', 'display':'gc总耗时(ms)'},
            {'name':'jvm.metrics.logError', 'display':'jvm error 次数'},
            {'name':'jvm.metrics.logFatal', 'display':'jvm 出现fatal次数'},
            {'name':'jvm.metrics.logInfo', 'display':'jvm info出现次数'},
            {'name':'jvm.metrics.logWarn', 'display':'jvm warn出现次数'},
            {'name':'jvm.metrics.maxMemoryM', 'display':'jvm最大内存（M）'},
            {'name':'jvm.metrics.memHeapCommittedM', 'display':'jvm提交堆内存大小'},
            {'name':'jvm.metrics.memHeapUsedM', 'display':'jvm使用堆内存大小'},
            {'name':'jvm.metrics.memNonHeapCommittedM', 'display':'jvm非堆内存已提交大小'},
            {'name':'jvm.metrics.memNonHeapUsedM', 'display':'jvm非堆内存已使用大小'},
            {'name':'jvm.metrics.threadsBlocked', 'display':'阻塞等待监视器锁的线程数'},
            {'name':'jvm.metrics.threadsNew', 'display':'尚未启动的线程数'},
            {'name':'jvm.metrics.threadsRunnable', 'display':'正在执行状态的线程数'},
            {'name':'jvm.metrics.threadsTerminated', 'display':'已退出线程数'},
            {'name':'jvm.metrics.threadsTimedWaiting', 'display':'等待并指定了等待时间的线程数'},
            {'name':'jvm.metrics.threadsWaiting', 'display':'无限期地等待特定操作的线程数目'},
        ],
            
        'hadoop-mapred':[
            {'name':'mapred.MRAppMetrics.jobsSubmitted', 'display':'提交的job数量'},
            {'name':'mapred.MRAppMetrics.jobsCompleted', 'display':'完成的job数量'},
            {'name':'mapred.MRAppMetrics.jobsFailed', 'display':'失败的job的数量'},
            {'name':'mapred.MRAppMetrics.jobsKilled', 'display':'终止的job的数量'},
            {'name':'mapred.MRAppMetrics.jobsPreparing', 'display':'正在准备的job的数量'},
            {'name':'mapred.MRAppMetrics.jobsRunning', 'display':'正在运行的job的数量'},
            {'name':'mapred.MRAppMetrics.MapsLaunched', 'display':'创建运行map的数量'},
            {'name':'mapred.MRAppMetrics.MapsCompleted', 'display':'完成的map的数量'},
            {'name':'mapred.MRAppMetrics.mapsFailed', 'display':'map失败的数量'},
            {'name':'mapred.MRAppMetrics.mapsKilled', 'display':'map终止的数量'},
            {'name':'mapred.MRAppMetrics.MapsRunning', 'display':'正在执行的map数量'},
            {'name':'mapred.MRAppMetrics.MapsWaiting', 'display':'正在等待的map数量'},
            {'name':'mapred.MRAppMetrics.ReducersLaunched', 'display':'创建运行的reducer数量'},
            {'name':'mapred.MRAppMetrics.ReducersCompleted', 'display':'完成的reducer数量'},
            {'name':'mapred.MRAppMetrics.ReducersFailed', 'display':'失败的reducer数量'},
            {'name':'mapred.MRAppMetrics.ReducersKilled', 'display':'终止的reducer数量'},
            {'name':'mapred.MRAppMetrics.ReducersRunning', 'display':'正在执行的reducer数量'},
            {'name':'mapred.MRAppMetrics.ReducersWaiting', 'display':'正在等待的reducer数量'},
            {'name':'mapred.ShuffleMetrics.ShuffleConnections', 'display':'当前的shuffle连接次数'},
            {'name':'mapred.ShuffleMetrics.ShuffleOutputBytes', 'display':'shuffle过程的传输流量'},
            {'name':'mapred.ShuffleMetrics.ShuffleOutputsOK', 'display':'shuffle传输成功的次数'},
            {'name':'mapred.ShuffleMetrics.shuffleOutputsFailed', 'display':'shuffle传输失败的次数'},
        ],
            
        'hadoop-rpc':[
            {'name':'rpc.rpc.callQueueLength', 'display':'排队队列长度'},
            {'name':'rpc.rpc.numOpenConnections', 'display':'打开的RPC连接'},
            {'name':'rpc.rpc.receivedBytes', 'display':'RPC获取的字节'},
            {'name':'rpc.rpc.rpcAuthorizationSuccesses', 'display':'RPC授权成功'},
            {'name':'rpc.rpc.RpcProcessingTimeAvgTime', 'display':'rpc.rpc.RpcProcessingTimeAvgTime'},
            {'name':'rpc.rpc.RpcProcessingTimeNumOps', 'display':'rpc.rpc.RpcProcessingTimeNumOps'},
            {'name':'rpc.rpc.RpcQueueTimeAvgTime', 'display':'rpc.rpc.RpcQueueTimeAvgTime'},
            {'name':'rpc.rpc.RpcQueueTimeNumOps', 'display':'rpc.rpc.RpcQueueTimeNumOps'},
            {'name':'rpc.rpc.sentBytes', 'display':'RPC发送的字节'},
            {'name':'rpc.rpc.rpcQueueTime', 'display':'RPC请求队列等待时间'},
            {'name':'rpc.rpc.rpcProcessingTime', 'display':'RPC请求的处理时间'},
            {'name':'rpc.rpc.rpcAuthenticationFailures', 'display':'RPC认证失败'},
            {'name':'rpc.rpc.rpcAuthenticationSuccesses', 'display':'RPC认证成功'},
            {'name':'rpc.rpc.rpcAuthorizationFailures', 'display':'RPC授权失败'},
        ],

        'hadoop-rpc-detailed':[
            {'name':'rpcdetailed.rpcdetailed.BlockReportAvgTime', 'display':'rpcdetailed.rpcdetailed.BlockReportAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.BlockReportNumOps', 'display':'rpcdetailed.rpcdetailed.BlockReportNumOps'},
            {'name':'rpcdetailed.rpcdetailed.GetListingAvgTime', 'display':'rpcdetailed.rpcdetailed.GetListingAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.GetListingNumOps', 'display':'rpcdetailed.rpcdetailed.GetListingNumOps'},
            {'name':'rpcdetailed.rpcdetailed.GetServiceStatusAvgTime', 'display':'rpcdetailed.rpcdetailed.GetServiceStatusAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.GetServiceStatusNumOps', 'display':'rpcdetailed.rpcdetailed.GetServiceStatusNumOps'},
            {'name':'rpcdetailed.rpcdetailed.MonitorHealthAvgTime', 'display':'rpcdetailed.rpcdetailed.MonitorHealthAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.MonitorHealthNumOps', 'display':'rpcdetailed.rpcdetailed.MonitorHealthNumOps'},
            {'name':'rpcdetailed.rpcdetailed.RegisterDatanodeAvgTime', 'display':'rpcdetailed.rpcdetailed.RegisterDatanodeAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.RegisterDatanodeNumOps', 'display':'rpcdetailed.rpcdetailed.RegisterDatanodeNumOps'},
            {'name':'rpcdetailed.rpcdetailed.RollEditLogAvgTime', 'display':'rpcdetailed.rpcdetailed.RollEditLogAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.RollEditLogNumOps', 'display':'rpcdetailed.rpcdetailed.RollEditLogNumOps'},
            {'name':'rpcdetailed.rpcdetailed.SendHeartbeatAvgTime', 'display':'rpcdetailed.rpcdetailed.SendHeartbeatAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.SendHeartbeatNumOps', 'display':'rpcdetailed.rpcdetailed.SendHeartbeatNumOps'},
            {'name':'rpcdetailed.rpcdetailed.TransitionToActiveAvgTime', 'display':'rpcdetailed.rpcdetailed.TransitionToActiveAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.TransitionToActiveNumOps', 'display':'rpcdetailed.rpcdetailed.TransitionToActiveNumOps'},
            {'name':'rpcdetailed.rpcdetailed.TransitionToStandbyAvgTime', 'display':'rpcdetailed.rpcdetailed.TransitionToStandbyAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.TransitionToStandbyNumOps', 'display':'rpcdetailed.rpcdetailed.TransitionToStandbyNumOps'},
            {'name':'rpcdetailed.rpcdetailed.VersionRequestAvgTime', 'display':'rpcdetailed.rpcdetailed.VersionRequestAvgTime'},
            {'name':'rpcdetailed.rpcdetailed.VersionRequestNumOps', 'display':'rpcdetailed.rpcdetailed.VersionRequestNumOps'},
        ],
            
        'hadoop-yarn-nodemanager':[
            {'name':'yarn.NodeManagerMetrics.containersLaunched', 'display':'登录的container数量'},
            {'name':'yarn.NodeManagerMetrics.containersCompleted', 'display':'container完成的数量'},
            {'name':'yarn.NodeManagerMetrics.containersFailed', 'display':'container失败的数量'},
            {'name':'yarn.NodeManagerMetrics.containersKilled', 'display':'container终止的数量'},
            {'name':'yarn.NodeManagerMetrics.containersIniting', 'display':'正在init的container'},
            {'name':'yarn.NodeManagerMetrics.containersRunning', 'display':'正在运行的container'},
            {'name':'yarn.NodeManagerMetrics.allocatedGB', 'display':'分配了多少GB内存'},
            {'name':'yarn.NodeManagerMetrics.allocatedContainers', 'display':'分配了多少container'},
            {'name':'yarn.NodeManagerMetrics.availableGB', 'display':'剩下可用内存'},
        ],
            
        'hadoop-ClusterMetrics':[
            {'name':'yarn.ClusterMetrics.numActiveNMs', 'display':'活跃的node'},
            {'name':'yarn.ClusterMetrics.numDecommissionedNMs', 'display':'排除的node'},
            {'name':'yarn.ClusterMetrics.numLostNMs', 'display':'lost的node'},
            {'name':'yarn.ClusterMetrics.numUnhealthyNMs', 'display':'不健康的node'},
            {'name':'yarn.ClusterMetrics.numRebootedNMs', 'display':'重启的node'},
        ],
            
        'hadoop-yarn-QueueMetrics':[
            {'name':'yarn.QueueMetrics.Queue=root.low.appsRunning', 'display':'运行的应用数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.appsPending', 'display':'待运行的应用数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.appsCompleted', 'display':'完成的应用数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.appsKilled', 'display':'终止的应用数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.appsFailed', 'display':'失败的应用数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.allocatedMB', 'display':'分配的内存量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.allocatedContainers', 'display':'分配的容器数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.aggregateContainersAllocated', 'display':'总容器分配数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.aggregateContainersReleased', 'display':'总容器释放数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.availableMB', 'display':'可用的内存量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.pendingMB', 'display':'需要的内存量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.pendingContainers', 'display':'待分配的容器数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.reservedMB', 'display':'预定的内存数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.reservedContainers', 'display':'预定的容器数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.activeUsers', 'display':'当前的用户数'},
            {'name':'yarn.QueueMetrics.Queue=root.low.activeApplications', 'display':'活跃的应用数量'},
            {'name':'yarn.QueueMetrics.Queue=root.low.running_60', 'display':'应用运行时间的分布'},
        ],
            
        'hbase-master-jvm':[
            {'name':'hbasemaster_memory_memNonHeapCommitted', 'display':'非堆的提交内存'},
            {'name':'hbasemaster_memory_memHeapCommitted', 'display':'堆的提交的内存'},
            {'name':'hbasemaster_memory_memNonHeapUsed', 'display':'非堆的使用的内存'},
            {'name':'hbasemaster_memory_memHeapUsed', 'display':'堆的使用的内存'},
            {'name':'hbasemaster_memory_memHeapMax', 'display':'堆的可用最大内存'},
            {'name':'hbasemaster_memory_memNonHeapMax', 'display':'非堆的最大内存'},
            {'name':'hbasemaster_gccms_gcCount', 'display':'CMS进行GC次数'},
            {'name':'hbasemaster_gccms_gcTime', 'display':'CMS进行GC时间'},
            {'name':'hbasemaster_gcparnew_gcCount', 'display':'ParNew进行GC次数'},
            {'name':'hbasemaster_gcparnew_gcTime', 'display':'ParNew进行GC时间'},
            {'name':'hbasemaster_Threading_ThreadCount', 'display':'线程数量'},
        ],
            
        'hbase-master':[
            {'name':'hbase.master_master_cluster_requests', 'display':'当前机器整体request的个数'},
            {'name':'hbase.master.splitSize_avg_time', 'display':'splitlog的大小'},
            {'name':'hbase.master.splitSize_num_ops', 'display':'splitlog次数'},
            {'name':'hbase.master.splitTime_avg_time', 'display':'splitlog的时间'},
            {'name':'hbase.master.splitTime_num_ops', 'display':'splitlog的次数'},
        ],
            
        'hbase-regionserver':[
            {'name':'hbase.regionserver.blockCacheCount', 'display':'BlockCache中缓存的block个数'},
            {'name':'hbase.regionserver.blockCacheEvictedCount', 'display':'BlockCache中被换出的Block的个数'},
            {'name':'hbase.regionserver.blockCacheFree', 'display':'blockcache中空闲的内存大小*'},
            {'name':'hbase.regionserver.blockCacheHitCachingRatio', 'display':'cacheblock的cache比率'},
            {'name':'hbase.regionserver.blockCacheHitCount', 'display':'blockCache命中次数  *'},
            {'name':'hbase.regionserver.blockCacheHitRatio', 'display':'blockCache命中比例  *'},
            {'name':'hbase.regionserver.blockCacheMissCount', 'display':'blockCache非命中比例'},
            {'name':'hbase.regionserver.blockCacheSize', 'display':'blockCache大小  *'},
            {'name':'hbase.regionserver.compactionQueueSize', 'display':'compaction Queue的大小  *'},
            {'name':'hbase.regionserver.compactionSize_avg_time', 'display':'平均执行一次Compaction的数据大小    *'},
            {'name':'hbase.regionserver.compactionSize_num_ops', 'display':'执行compaction的次数    *'},
            {'name':'hbase.regionserver.compactionTime_avg_time', 'display':'平均执行一次Compaction的时间    *'},
            {'name':'hbase.regionserver.compactionTime_num_ops', 'display':'执行compaction的次数    *'},
            {'name':'hbase.regionserver.deleteRequestLatency_75th_percentile', 'display':'75%的删除请求延时的概率统计'},
            {'name':'hbase.regionserver.deleteRequestLatency_95th_percentile', 'display':'95%的删除请求延时的概率统计'},
            {'name':'hbase.regionserver.deleteRequestLatency_99th_percentile', 'display':'99%的删除请求延时的概率统计'},
            {'name':'hbase.regionserver.deleteRequestLatency_max', 'display':'删除请求的最大值'},
            {'name':'hbase.regionserver.deleteRequestLatency_mean', 'display':'删除请求的平均值'},
            {'name':'hbase.regionserver.deleteRequestLatency_median', 'display':'删除请求的中位值'},
            {'name':'hbase.regionserver.deleteRequestLatency_min', 'display':'删除请求的最小值'},
            {'name':'hbase.regionserver.deleteRequestLatency_num_ops', 'display':'删除请求的个数'},
            {'name':'hbase.regionserver.deleteRequestLatency_std_dev', 'display':'删除请求的标准差'},
            {'name':'hbase.regionserver.flushQueueSize', 'display':'flush Queue的大小   *'},
            {'name':'hbase.regionserver.flushSize_avg_time', 'display':'平均执行一次flush的数据大小 *'},
            {'name':'hbase.regionserver.flushSize_num_ops', 'display':'执行flush的次数 *'},
            {'name':'hbase.regionserver.flushTime_avg_time', 'display':'平均执行一次flush的时间 *'},
            {'name':'hbase.regionserver.flushTime_num_ops', 'display':'执行flush的次数 *'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_75th_percentile', 'display':'75%的读HLog时间的概率统计'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_95th_percentile', 'display':'95%的读HLog时间的概率统计'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_99th_percentile', 'display':'99%的读HLog时间的概率统计'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_max', 'display':'读HLog时间的最大值'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_mean', 'display':'读HLog时间的平均值'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_median', 'display':'读HLog时间的中位值'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_min', 'display':'读HLog时间的最小值'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_num_ops', 'display':'读HLog的次数'},
            {'name':'hbase.regionserver.fsReadLatencyHistogram_std_dev', 'display':'读HLog时间的标准差'},
            {'name':'hbase.regionserver.fsReadLatency_avg_time', 'display':'读HLog时间的平均时间'},
            {'name':'hbase.regionserver.fsReadLatency_num_ops', 'display':'读HLog时间的次数'},
            {'name':'hbase.regionserver.fsSyncLatency_avg_time', 'display':'sync HLog的平均时间'},
            {'name':'hbase.regionserver.fsSyncLatency_num_ops', 'display':'sync HLog的次数'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_75th_percentil', 'display':'75%的写HLog的概率统计'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_95th_percentil', 'display':'95%的写HLog的概率统计'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_99th_percentil', 'display':'99%的写HLog的概率统计'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_max', 'display':'写HLog时间的最大值'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_mean', 'display':'写HLog时间的最大值'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_median', 'display':'写HLog时间的最大值'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_min', 'display':'写HLog时间的最大值'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_num_ops', 'display':'写HLog的次数'},
            {'name':'hbase.regionserver.fsWriteLatencyHistogram_std_dev', 'display':'写HLog时间的标准差'},
            {'name':'hbase.regionserver.fsWriteLatency_avg_time', 'display':'写HLog操作的平均Latency'},
            {'name':'hbase.regionserver.fsWriteLatency_num_ops', 'display':'写HLog操作的次数'},
            {'name':'hbase.regionserver.getRequestLatency_75th_percentile', 'display':'75%的get请求时间的概率统计'},
            {'name':'hbase.regionserver.getRequestLatency_95th_percentile', 'display':'95%的get请求时间的概率统计'},
            {'name':'hbase.regionserver.getRequestLatency_99th_percentile', 'display':'99%的get请求时间的概率统计'},
            {'name':'hbase.regionserver.getRequestLatency_max', 'display':'get请求时间的最大值'},
            {'name':'hbase.regionserver.getRequestLatency_mean', 'display':'get请求时间的平均值'},
            {'name':'hbase.regionserver.getRequestLatency_median', 'display':'get请求时间的中位值'},
            {'name':'hbase.regionserver.getRequestLatency_min', 'display':'get请求时间的最小值'},
            {'name':'hbase.regionserver.getRequestLatency_num_ops', 'display':'get请求的次数'},
            {'name':'hbase.regionserver.getRequestLatency_std_dev', 'display':'get请求时间的标准差'},
            {'name':'hbase.regionserver.hdfsBlocksLocalityIndex', 'display':'所在机器的数据本地化的概率'},
            {'name':'hbase.regionserver.hlogFileCount', 'display':'hlog file的个数'},
            {'name':'hbase.regionserver.mbInMemoryWithoutWAL', 'display':'不写WAL的Put操作的数据在Memstore占用的空间'},
            {'name':'hbase.regionserver.memstoreSizeMB', 'display':'HRegion中的memstore大小的总和 *'},
            {'name':'hbase.regionserver.numPutsWithoutWAL', 'display':'不写WAL(Write-Ahead-Log)的Put操作的个数'},
            {'name':'hbase.regionserver.putRequestLatency_75th_percentile', 'display':'75%的put请求时间的概率统计'},
            {'name':'hbase.regionserver.putRequestLatency_95th_percentile', 'display':'95%的put请求时间的概率统计'},
            {'name':'hbase.regionserver.putRequestLatency_99th_percentile', 'display':'99%的put请求时间的概率统计'},
            {'name':'hbase.regionserver.putRequestLatency_max', 'display':'put请求时间的最大值'},
            {'name':'hbase.regionserver.putRequestLatency_mean', 'display':'put请求时间的平均值'},
            {'name':'hbase.regionserver.putRequestLatency_median', 'display':'put请求时间的中位值'},
            {'name':'hbase.regionserver.putRequestLatency_min', 'display':'put请求时间的最小值'},
            {'name':'hbase.regionserver.putRequestLatency_num_ops', 'display':'put请求的次数'},
            {'name':'hbase.regionserver.putRequestLatency_std_dev', 'display':'put请求时间的标准差'},
            {'name':'hbase.regionserver.readRequestsCount', 'display':'读请求的数量 *'},
            {'name':'hbase.regionserver.regionSplitFailureCount', 'display':'region split失败的次数'},
            {'name':'hbase.regionserver.regionSplitSuccessCount', 'display':'region split成功的次数'},
            {'name':'hbase.regionserver.regions', 'display':'region的个数 *'},
            {'name':'hbase.regionserver.requests', 'display':'请求的数量  *'},
            {'name':'hbase.regionserver.rootIndexSizeKB', 'display':'storefileIndex的大小'},
            {'name':'hbase.regionserver.storefileIndexSizeMB', 'display':'storefileIndex的大小'},
            {'name':'hbase.regionserver.storefiles', 'display':'所有的Storefiles的个数    *'},
            {'name':'hbase.regionserver.stores', 'display':'Store的个数   *'},
            {'name':'hbase.regionserver.totalStaticBloomSizeKB', 'display':'所有Store上的BloomFilter大小'},
            {'name':'hbase.regionserver.totalStaticIndexSizeKB', 'display':'HFile文件的IndexSize的大小*'},
            {'name':'hbase.regionserver.writeRequestsCount', 'display':'写请求的数量'},
        ],
            
        'custom':[
            {'name':'disk_smartctl_sda_Power_On_Hours', 'display':'通电时间'},
            {'name':'disk_smartctl_sda_Runtime_Bad_Block', 'display':'运行时坏的块'},
            {'name':'disk_smartctl_sda_Raw_Read_Error_Rate', 'display':'读取磁盘的时候发生错误的次数'},
            {'name':'disk_smartctl_sda_Seek_Error_Rate', 'display':'磁头移动错误率'},
            {'name':'disk_smartctl_sda_UDMA_CRC_error_count', 'display':'数据传输校验的错误次数'},
            {'name':'disk_iostat_sda1_rrqm_s', 'display':'每秒读请求Merge'},
            {'name':'disk_iostat_sda1_wrqm_s', 'display':'每秒写请求Merge'},
            {'name':'disk_iostat_sda1_r_s', 'display':'每秒的读请求'},
            {'name':'disk_iostat_sda1_w_s', 'display':'每秒的写请求'},
            {'name':'disk_iostat_sda1_rkB_s', 'display':'每秒读K字节数'},
            {'name':'disk_iostat_sda1_wkB_s', 'display':'每秒写K字节数'},
            {'name':'disk_iostat_sda1_avgrq-sz', 'display':'平均每次设备I/O操作的数据大小'},
            {'name':'disk_iostat_sda1_avgqu-sz', 'display':'平均I/O队列长度'},
            {'name':'disk_iostat_sda1_await', 'display':'每一个IO请求的处理的平均时间'},
            {'name':'disk_iostat_sda1_r_await', 'display':'读操作的await'},
            {'name':'disk_iostat_sda1_w_await', 'display':'写操作的await'},
            {'name':'disk_iostat_sda1_svctm', 'display':'平均每次设备I/O操作的服务时间'},
            {'name':'disk_iostat_sda1_util', 'display':'设备的繁忙程度'},
            {'name':'servicestat_zookeeper_cpu_percent', 'display':'CPU占用比率'},
            {'name':'servicestat_zookeeper_exist_exist', 'display':'这个服务是否存在'},
            {'name':'servicestat_zookeeper_io_bytes_read', 'display':'磁盘读取量'},
            {'name':'servicestat_zookeeper_io_bytes_write', 'display':'磁盘写入量'},
            {'name':'servicestat_zookeeper_io_count_read', 'display':'磁盘读取次数'},
            {'name':'servicestat_zookeeper_io_count_write', 'display':'磁盘写入次数'},
            {'name':'servicestat_zookeeper_mem_rss', 'display':'内存使用量'},
            {'name':'servicestat_zookeeper_mem_vms', 'display':'虚拟内存使用量'},
        ],

        'unknown':[
            {'name':'metricssystem.MetricsSystem.DroppedPubAll', 'display':'metricssystem.MetricsSystem.DroppedPubAll     '},
            {'name':'metricssystem.MetricsSystem.NumActiveSinks', 'display':'metricssystem.MetricsSystem.NumActiveSinks'},
            {'name':'metricssystem.MetricsSystem.NumActiveSources', 'display':'metricssystem.MetricsSystem.NumActiveSources'},
            {'name':'metricssystem.MetricsSystem.NumAllSinks', 'display':'metricssystem.MetricsSystem.NumAllSinks'},
            {'name':'metricssystem.MetricsSystem.NumAllSources', 'display':'metricssystem.MetricsSystem.NumAllSources'},
            {'name':'metricssystem.MetricsSystem.PublishAvgTime', 'display':'metricssystem.MetricsSystem.PublishAvgTime'},
            {'name':'metricssystem.MetricsSystem.PublishNumOps', 'display':'metricssystem.MetricsSystem.PublishNumOps'},
            {'name':'metricssystem.MetricsSystem.Sink_gangliaAvgTime', 'display':'metricssystem.MetricsSystem.Sink_gangliaAvgTime'},
            {'name':'metricssystem.MetricsSystem.Sink_gangliaNumOps', 'display':'metricssystem.MetricsSystem.Sink_gangliaNumOps'},
            {'name':'metricssystem.MetricsSystem.SnapshotAvgTime', 'display':'metricssystem.MetricsSystem.SnapshotAvgTime'},
            {'name':'metricssystem.MetricsSystem.SnapshotNumOps', 'display':'metricssystem.MetricsSystem.SnapshotNumOps    '},
        ]
    }
}
# ~ monitor_show_info

services_metrics = [
    {    
        'name':'hdfs','show':[
            {'name':'instance-status', 'display':'实体状态', 'type':'instance-status', 'role':'namenode', 'metric':'dfs.FSNamesystem.HAState'},
            {'name':'metrics', 'display':'指标', 'type':'list', 'role':'namenode', 'metric-groups':['hadoop-dfs-FSNamesystem'],},
        ],
    },
    {   'name':'yarn', 'show':[ 
            {'name':'metrics', 'display':'指标', 'type':'list', 'role':'resourcemanager', 'metric-groups':['hadoop-mapred','hadoop-ClusterMetrics','hadoop-yarn-QueueMetrics'],},
        ],
    },
]
# ~ services_metrics

# 为网卡上限设置一个值
bytes_top = 1024 * 1024 * 128 # 128M  for 1G
host_load_percent_expression = "load_one*100/cpu_num"
host_mem_percent_expression  = "(mem_total - mem_free - mem_cached - mem_buffers)*100/mem_total"
host_net_percent_expression  = "(bytes_in + bytes_out)*100 / %d" % bytes_top
host_disk_percent_expression = "(disk_total - disk_free)*100/disk_total"

